include: package:very_good_analysis/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
  exclude:
    - build/**
    - android/**
    - ios/**
    - windows/**
    - macos/**
    - linux/**

formatter:
  page_width: 80
  trailing_commas: automate
