// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/typst.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1665335970;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'typst_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiTypstTypstEngineAddFonts({
    required TypstEngine that,
    required List<Uint8List> fontData,
  });

  Future<int> crateApiTypstTypstEngineCompileDocument({
    required TypstEngine that,
    required String markup,
    required List<VirtualFile> files,
    PlatformInt64? sysTime,
  });

  Future<TypstResult> crateApiTypstTypstEngineCompilePdf({
    required TypstEngine that,
    required String markup,
    required List<VirtualFile> files,
    PlatformInt64? sysTime,
  });

  Future<List<String>> crateApiTypstTypstEngineCompileSvg({
    required TypstEngine that,
    required String markup,
    required List<VirtualFile> files,
    PlatformInt64? sysTime,
  });

  TypstEngine crateApiTypstTypstEngineNew();

  Future<RenderResult> crateApiTypstTypstEngineRenderCachedPage({
    required TypstEngine that,
    required BigInt pageIndex,
    required double pixelPerPt,
  });

  Future<String> crateApiTypstTypstEngineRenderCachedPageAsSvg({
    required TypstEngine that,
    required BigInt pageIndex,
  });

  Future<RenderResult> crateApiTypstTypstEngineRenderPage({
    required TypstEngine that,
    required String markup,
    required List<VirtualFile> files,
    required BigInt pageIndex,
    required double pixelPerPt,
    PlatformInt64? sysTime,
  });

  Future<Uint8List> crateApiTypstTypstEngineRenderPageAsPng({
    required TypstEngine that,
    required String markup,
    required List<VirtualFile> files,
    required BigInt pageIndex,
    required double pixelPerPt,
    PlatformInt64? sysTime,
  });

  Future<String> crateApiTypstGetTypstVersion();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TypstEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TypstEngine;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TypstEnginePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiTypstTypstEngineAddFonts({
    required TypstEngine that,
    required List<Uint8List> fontData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
            that,
            serializer,
          );
          sse_encode_list_list_prim_u_8_strict(fontData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypstTypstEngineAddFontsConstMeta,
        argValues: [that, fontData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypstTypstEngineAddFontsConstMeta =>
      const TaskConstMeta(
        debugName: "TypstEngine_add_fonts",
        argNames: ["that", "fontData"],
      );

  @override
  Future<int> crateApiTypstTypstEngineCompileDocument({
    required TypstEngine that,
    required String markup,
    required List<VirtualFile> files,
    PlatformInt64? sysTime,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
            that,
            serializer,
          );
          sse_encode_String(markup, serializer);
          sse_encode_list_virtual_file(files, serializer);
          sse_encode_opt_box_autoadd_i_64(sysTime, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_typst_compile_error,
        ),
        constMeta: kCrateApiTypstTypstEngineCompileDocumentConstMeta,
        argValues: [that, markup, files, sysTime],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypstTypstEngineCompileDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "TypstEngine_compile_document",
        argNames: ["that", "markup", "files", "sysTime"],
      );

  @override
  Future<TypstResult> crateApiTypstTypstEngineCompilePdf({
    required TypstEngine that,
    required String markup,
    required List<VirtualFile> files,
    PlatformInt64? sysTime,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
            that,
            serializer,
          );
          sse_encode_String(markup, serializer);
          sse_encode_list_virtual_file(files, serializer);
          sse_encode_opt_box_autoadd_i_64(sysTime, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_typst_result,
          decodeErrorData: sse_decode_typst_compile_error,
        ),
        constMeta: kCrateApiTypstTypstEngineCompilePdfConstMeta,
        argValues: [that, markup, files, sysTime],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypstTypstEngineCompilePdfConstMeta =>
      const TaskConstMeta(
        debugName: "TypstEngine_compile_pdf",
        argNames: ["that", "markup", "files", "sysTime"],
      );

  @override
  Future<List<String>> crateApiTypstTypstEngineCompileSvg({
    required TypstEngine that,
    required String markup,
    required List<VirtualFile> files,
    PlatformInt64? sysTime,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
            that,
            serializer,
          );
          sse_encode_String(markup, serializer);
          sse_encode_list_virtual_file(files, serializer);
          sse_encode_opt_box_autoadd_i_64(sysTime, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_typst_compile_error,
        ),
        constMeta: kCrateApiTypstTypstEngineCompileSvgConstMeta,
        argValues: [that, markup, files, sysTime],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypstTypstEngineCompileSvgConstMeta =>
      const TaskConstMeta(
        debugName: "TypstEngine_compile_svg",
        argNames: ["that", "markup", "files", "sysTime"],
      );

  @override
  TypstEngine crateApiTypstTypstEngineNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypstTypstEngineNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypstTypstEngineNewConstMeta =>
      const TaskConstMeta(debugName: "TypstEngine_new", argNames: []);

  @override
  Future<RenderResult> crateApiTypstTypstEngineRenderCachedPage({
    required TypstEngine that,
    required BigInt pageIndex,
    required double pixelPerPt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
            that,
            serializer,
          );
          sse_encode_usize(pageIndex, serializer);
          sse_encode_f_32(pixelPerPt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTypstTypstEngineRenderCachedPageConstMeta,
        argValues: [that, pageIndex, pixelPerPt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypstTypstEngineRenderCachedPageConstMeta =>
      const TaskConstMeta(
        debugName: "TypstEngine_render_cached_page",
        argNames: ["that", "pageIndex", "pixelPerPt"],
      );

  @override
  Future<String> crateApiTypstTypstEngineRenderCachedPageAsSvg({
    required TypstEngine that,
    required BigInt pageIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
            that,
            serializer,
          );
          sse_encode_usize(pageIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTypstTypstEngineRenderCachedPageAsSvgConstMeta,
        argValues: [that, pageIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypstTypstEngineRenderCachedPageAsSvgConstMeta =>
      const TaskConstMeta(
        debugName: "TypstEngine_render_cached_page_as_svg",
        argNames: ["that", "pageIndex"],
      );

  @override
  Future<RenderResult> crateApiTypstTypstEngineRenderPage({
    required TypstEngine that,
    required String markup,
    required List<VirtualFile> files,
    required BigInt pageIndex,
    required double pixelPerPt,
    PlatformInt64? sysTime,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
            that,
            serializer,
          );
          sse_encode_String(markup, serializer);
          sse_encode_list_virtual_file(files, serializer);
          sse_encode_usize(pageIndex, serializer);
          sse_encode_f_32(pixelPerPt, serializer);
          sse_encode_opt_box_autoadd_i_64(sysTime, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_result,
          decodeErrorData: sse_decode_typst_compile_error,
        ),
        constMeta: kCrateApiTypstTypstEngineRenderPageConstMeta,
        argValues: [that, markup, files, pageIndex, pixelPerPt, sysTime],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypstTypstEngineRenderPageConstMeta =>
      const TaskConstMeta(
        debugName: "TypstEngine_render_page",
        argNames: [
          "that",
          "markup",
          "files",
          "pageIndex",
          "pixelPerPt",
          "sysTime",
        ],
      );

  @override
  Future<Uint8List> crateApiTypstTypstEngineRenderPageAsPng({
    required TypstEngine that,
    required String markup,
    required List<VirtualFile> files,
    required BigInt pageIndex,
    required double pixelPerPt,
    PlatformInt64? sysTime,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
            that,
            serializer,
          );
          sse_encode_String(markup, serializer);
          sse_encode_list_virtual_file(files, serializer);
          sse_encode_usize(pageIndex, serializer);
          sse_encode_f_32(pixelPerPt, serializer);
          sse_encode_opt_box_autoadd_i_64(sysTime, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_typst_compile_error,
        ),
        constMeta: kCrateApiTypstTypstEngineRenderPageAsPngConstMeta,
        argValues: [that, markup, files, pageIndex, pixelPerPt, sysTime],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypstTypstEngineRenderPageAsPngConstMeta =>
      const TaskConstMeta(
        debugName: "TypstEngine_render_page_as_png",
        argNames: [
          "that",
          "markup",
          "files",
          "pageIndex",
          "pixelPerPt",
          "sysTime",
        ],
      );

  @override
  Future<String> crateApiTypstGetTypstVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypstGetTypstVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypstGetTypstVersionConstMeta =>
      const TaskConstMeta(debugName: "get_typst_version", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TypstEngine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TypstEngine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine;

  @protected
  TypstEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TypstEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TypstEngine
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TypstEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TypstEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TypstEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TypstEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TypstEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TypstDiagnostic> dco_decode_list_typst_diagnostic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_typst_diagnostic).toList();
  }

  @protected
  List<VirtualFile> dco_decode_list_virtual_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_virtual_file).toList();
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  RenderResult dco_decode_render_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RenderResult(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  TypstCompileError dco_decode_typst_compile_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return TypstCompileError(
      diagnostics: dco_decode_list_typst_diagnostic(arr[0]),
    );
  }

  @protected
  TypstDiagnostic dco_decode_typst_diagnostic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TypstDiagnostic(
      severity: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
      hints: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  TypstResult dco_decode_typst_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TypstResult(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      pageCount: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VirtualFile dco_decode_virtual_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return VirtualFile(
      path: dco_decode_String(arr[0]),
      bytes: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  TypstEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TypstEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TypstEngine
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TypstEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TypstEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TypstEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TypstEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TypstEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TypstDiagnostic> sse_decode_list_typst_diagnostic(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TypstDiagnostic>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_typst_diagnostic(deserializer));
    }
    return ans_;
  }

  @protected
  List<VirtualFile> sse_decode_list_virtual_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VirtualFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_virtual_file(deserializer));
    }
    return ans_;
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RenderResult sse_decode_render_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return RenderResult(bytes: var_bytes, width: var_width, height: var_height);
  }

  @protected
  TypstCompileError sse_decode_typst_compile_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_diagnostics = sse_decode_list_typst_diagnostic(deserializer);
    return TypstCompileError(diagnostics: var_diagnostics);
  }

  @protected
  TypstDiagnostic sse_decode_typst_diagnostic(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_severity = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_hints = sse_decode_list_String(deserializer);
    return TypstDiagnostic(
      severity: var_severity,
      message: var_message,
      hints: var_hints,
    );
  }

  @protected
  TypstResult sse_decode_typst_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_pageCount = sse_decode_u_32(deserializer);
    return TypstResult(bytes: var_bytes, pageCount: var_pageCount);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VirtualFile sse_decode_virtual_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return VirtualFile(path: var_path, bytes: var_bytes);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    TypstEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TypstEngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    TypstEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TypstEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    TypstEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TypstEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(
    TypstEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TypstEngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_typst_diagnostic(
    List<TypstDiagnostic> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_typst_diagnostic(item, serializer);
    }
  }

  @protected
  void sse_encode_list_virtual_file(
    List<VirtualFile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_virtual_file(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_render_result(RenderResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_typst_compile_error(
    TypstCompileError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_typst_diagnostic(self.diagnostics, serializer);
  }

  @protected
  void sse_encode_typst_diagnostic(
    TypstDiagnostic self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.severity, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_String(self.hints, serializer);
  }

  @protected
  void sse_encode_typst_result(TypstResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_u_32(self.pageCount, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_virtual_file(VirtualFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class TypstEngineImpl extends RustOpaque implements TypstEngine {
  // Not to be used by end users
  TypstEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TypstEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TypstEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TypstEngine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TypstEnginePtr,
  );

  /// Adds additional fonts to the engine.
  Future<void> addFonts({required List<Uint8List> fontData}) => RustLib
      .instance
      .api
      .crateApiTypstTypstEngineAddFonts(that: this, fontData: fontData);

  /// Compile a document and keep it in memory for fast rendering.
  ///
  /// Returns the total page count.
  Future<int> compileDocument({
    required String markup,
    required List<VirtualFile> files,
    PlatformInt64? sysTime,
  }) => RustLib.instance.api.crateApiTypstTypstEngineCompileDocument(
    that: this,
    markup: markup,
    files: files,
    sysTime: sysTime,
  );

  /// Compile Typst markup to PDF bytes.
  Future<TypstResult> compilePdf({
    required String markup,
    required List<VirtualFile> files,
    PlatformInt64? sysTime,
  }) => RustLib.instance.api.crateApiTypstTypstEngineCompilePdf(
    that: this,
    markup: markup,
    files: files,
    sysTime: sysTime,
  );

  /// Compiles Typst markup to a list of SVG strings (one per page).
  Future<List<String>> compileSvg({
    required String markup,
    required List<VirtualFile> files,
    PlatformInt64? sysTime,
  }) => RustLib.instance.api.crateApiTypstTypstEngineCompileSvg(
    that: this,
    markup: markup,
    files: files,
    sysTime: sysTime,
  );

  /// Renders a single page of the currently compiled document.
  Future<RenderResult> renderCachedPage({
    required BigInt pageIndex,
    required double pixelPerPt,
  }) => RustLib.instance.api.crateApiTypstTypstEngineRenderCachedPage(
    that: this,
    pageIndex: pageIndex,
    pixelPerPt: pixelPerPt,
  );

  /// Renders a single page of the currently compiled document as an SVG string.
  Future<String> renderCachedPageAsSvg({required BigInt pageIndex}) =>
      RustLib.instance.api.crateApiTypstTypstEngineRenderCachedPageAsSvg(
        that: this,
        pageIndex: pageIndex,
      );

  /// Render a single page of a Typst document to raw RGBA pixels.
  Future<RenderResult> renderPage({
    required String markup,
    required List<VirtualFile> files,
    required BigInt pageIndex,
    required double pixelPerPt,
    PlatformInt64? sysTime,
  }) => RustLib.instance.api.crateApiTypstTypstEngineRenderPage(
    that: this,
    markup: markup,
    files: files,
    pageIndex: pageIndex,
    pixelPerPt: pixelPerPt,
    sysTime: sysTime,
  );

  /// Renders a single page of a Typst document to PNG bytes.
  Future<Uint8List> renderPageAsPng({
    required String markup,
    required List<VirtualFile> files,
    required BigInt pageIndex,
    required double pixelPerPt,
    PlatformInt64? sysTime,
  }) => RustLib.instance.api.crateApiTypstTypstEngineRenderPageAsPng(
    that: this,
    markup: markup,
    files: files,
    pageIndex: pageIndex,
    pixelPerPt: pixelPerPt,
    sysTime: sysTime,
  );
}
