// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member

import 'package:flutter/cupertino.dart' as ui show Image;
import 'package:flutter/material.dart' as ui show Image;
import 'package:flutter/widgets.dart' as ui show Image;
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:typst_flutter/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_errors`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SimpleWorld`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `book`, `file`, `font`, `library`, `main`, `source`, `today`

/// Compile Typst markup to PDF bytes.
///
/// - [markup]  — Typst source text.
/// - [fonts]   — Raw bytes of font files to make available to the compiler.
/// - [files]   — Virtual files (images, data files, includes) the markup may
///               reference. Keys must match the paths used in markup exactly.
Future<TypstResult> compilePdf({
  required String markup,
  required List<Uint8List> fonts,
  required List<VirtualFile> files,
}) => RustLib.instance.api.crateApiTypstCompilePdf(
  markup: markup,
  fonts: fonts,
  files: files,
);

/// Render a single page of a Typst document to raw RGBA pixels.
///
/// - [markup]       — Typst source text.
/// - [fonts]        — Raw bytes of font files.
/// - [files]        — Virtual files the markup may reference.
/// - [page_index]   — Zero-based page index.
/// - [pixel_per_pt] — Pixels per typographic point (1pt = 1/72 inch).
///                    Use 2.0 for a crisp rendering on 2× displays.
///
/// Returns raw RGBA bytes (4 bytes per pixel), plus width and height.
/// Use [ui.ImageDescriptor.raw] on the Dart side to decode these into
/// a [ui.Image].
Future<RenderResult> renderPage({
  required String markup,
  required List<Uint8List> fonts,
  required List<VirtualFile> files,
  required BigInt pageIndex,
  required double pixelPerPt,
}) => RustLib.instance.api.crateApiTypstRenderPage(
  markup: markup,
  fonts: fonts,
  files: files,
  pageIndex: pageIndex,
  pixelPerPt: pixelPerPt,
);

/// Returns the version string of the embedded Typst compiler.
Future<String> getTypstVersion() =>
    RustLib.instance.api.crateApiTypstGetTypstVersion();

/// Result of rendering a single page.
class RenderResult {
  const RenderResult({
    required this.bytes,
    required this.width,
    required this.height,
  });

  /// Raw RGBA pixel data (4 bytes per pixel, row-major).
  final Uint8List bytes;

  /// Width of the rendered image in pixels.
  final int width;

  /// Height of the rendered image in pixels.
  final int height;

  @override
  int get hashCode => bytes.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          width == other.width &&
          height == other.height;
}

/// Result of a successful PDF compilation.
class TypstResult {
  const TypstResult({
    required this.bytes,
    required this.pageCount,
  });

  /// Raw PDF bytes.
  final Uint8List bytes;

  /// Total number of pages in the compiled document.
  final int pageCount;

  @override
  int get hashCode => bytes.hashCode ^ pageCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          pageCount == other.pageCount;
}

/// A virtual file to be made available to the Typst compiler.
///
/// The [path] must match exactly the path used in Typst markup.
/// For example, if the markup contains `#image("logo.png")`, the path
/// must be `"logo.png"`.
class VirtualFile {
  const VirtualFile({
    required this.path,
    required this.bytes,
  });

  /// The virtual path as referenced in Typst markup.
  final String path;

  /// The raw file bytes.
  final Uint8List bytes;

  @override
  int get hashCode => path.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VirtualFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          bytes == other.bytes;
}
