// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_fonts`, `map_errors`, `new`, `set_files`, `set_markup`, `set_sys_time`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SimpleWorld`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `book`, `clone`, `clone`, `clone`, `clone`, `clone`, `file`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `font`, `library`, `main`, `source`, `today`

Future<String> getTypstVersion() =>
    RustLib.instance.api.crateApiTypstGetTypstVersion();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CompiledDocument>>
abstract class CompiledDocument implements RustOpaqueInterface {
  /// Exports the document to a PDF byte array.
  Future<Uint8List> exportPdf();

  /// Exports a specific page to an SVG string.
  Future<String> exportSvg({required BigInt index});

  /// Returns the number of pages in the document.
  Future<BigInt> pageCount();

  /// Returns the dimensions of a page in points.
  Future<PageInfo> pageInfo({required BigInt index});

  /// Renders a specific page to raw RGBA pixels.
  Future<RenderResult> renderPage({
    required BigInt index,
    required double pixelPerPt,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TypstEngine>>
abstract class TypstEngine implements RustOpaqueInterface {
  /// Adds additional fonts to the engine.
  Future<void> addFonts({required List<Uint8List> fontData});

  /// Compile Typst markup into a CompiledDocument handle.
  Future<CompiledDocument> compile({
    required String markup,
    required List<VirtualFile> files,
    PlatformInt64? sysTime,
  });

  /// Creates a new Typst engine with bundled default fonts.
  factory TypstEngine() => RustLib.instance.api.crateApiTypstTypstEngineNew();
}

class PageInfo {
  final double widthPt;
  final double heightPt;

  const PageInfo({required this.widthPt, required this.heightPt});

  @override
  int get hashCode => widthPt.hashCode ^ heightPt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageInfo &&
          runtimeType == other.runtimeType &&
          widthPt == other.widthPt &&
          heightPt == other.heightPt;
}

/// Result of rendering a single page.
class RenderResult {
  /// Raw RGBA pixel data (4 bytes per pixel, row-major).
  final Uint8List bytes;

  /// Width of the rendered image in pixels.
  final int width;

  /// Height of the rendered image in pixels.
  final int height;

  const RenderResult({
    required this.bytes,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => bytes.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          width == other.width &&
          height == other.height;
}

class TypstCompileError implements FrbException {
  final List<TypstDiagnostic> diagnostics;

  const TypstCompileError({required this.diagnostics});

  @override
  int get hashCode => diagnostics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstCompileError &&
          runtimeType == other.runtimeType &&
          diagnostics == other.diagnostics;
}

class TypstDiagnostic {
  final String severity;
  final String message;
  final List<String> hints;

  const TypstDiagnostic({
    required this.severity,
    required this.message,
    required this.hints,
  });

  @override
  int get hashCode => severity.hashCode ^ message.hashCode ^ hints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypstDiagnostic &&
          runtimeType == other.runtimeType &&
          severity == other.severity &&
          message == other.message &&
          hints == other.hints;
}

/// A virtual file to be made available to the Typst compiler.
///
/// The [path] must match exactly the path used in Typst markup.
/// For example, if the markup contains `#image("logo.png")`, the path
/// must be `"logo.png"`.
class VirtualFile {
  /// The virtual path as referenced in Typst markup.
  final String path;

  /// The raw file bytes.
  final Uint8List bytes;

  const VirtualFile({required this.path, required this.bytes});

  @override
  int get hashCode => path.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VirtualFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          bytes == other.bytes;
}
